# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: SelfHosted

steps:
- script: |
    terraform version
     $env:USERNAME
  displayName: 'display terraform versions Terraform'
