# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: SelfHosted

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: azureLaps
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      $env:USERNAME

- script: |
    terraform version
  displayName: 'display terraform versions Terraform'
