# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: SelfHosted

steps:

- powershell: |
    if (-not (Get-Command az version -ErrorAction SilentlyContinue)) {
        Write-Host "Azure CLI not found. Installing..."
        Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'
    } else {
        Write-Host "Azure CLI is already installed."
    }

    # Confirm installation
    az version
  displayName: 'Check and Install Azure CLI'
- task: AzureCLI@2
  inputs:
    azureSubscription: azureLaps
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az account show

- script: |
    terraform version
  displayName: 'display terraform versions Terraform'
